name: do bad things
on:
    workflow_dispatch:

jobs:
    update:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4.2.2
            - name: bad things
              run: ./commit-test.sh
