name: do bad things
on:
    workflow_dispatch:

jobs:
    update:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4.2.2
            - name: bad things
              run: |
                git config --global user.name "anon"
                git config --global user.email "username@users.noreply.github.com"
                ./commit-test.sh
